//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 01:06:02 PM PDT 
//


package com.ibm.streamsx.topology.internal.toolkit.info;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for libraryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="libraryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.ibm.com/xmlns/prod/streams/spl/common}descriptionType"/>
 *         &lt;element name="managedLibrary" type="{http://www.ibm.com/xmlns/prod/streams/spl/common}managedLibraryType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "libraryType", namespace = "http://www.ibm.com/xmlns/prod/streams/spl/common", propOrder = {
    "description",
    "managedLibrary"
})
public class LibraryType {

    @XmlElement(required = true)
    protected DescriptionType description;
    @XmlElement(required = true)
    protected ManagedLibraryType managedLibrary;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptionType }
     *     
     */
    public DescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptionType }
     *     
     */
    public void setDescription(DescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the managedLibrary property.
     * 
     * @return
     *     possible object is
     *     {@link ManagedLibraryType }
     *     
     */
    public ManagedLibraryType getManagedLibrary() {
        return managedLibrary;
    }

    /**
     * Sets the value of the managedLibrary property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManagedLibraryType }
     *     
     */
    public void setManagedLibrary(ManagedLibraryType value) {
        this.managedLibrary = value;
    }

}
