//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 01:06:02 PM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo",
   elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED,
   xmlns={@XmlNs(prefix="info", namespaceURI="http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo")})
package com.ibm.streamsx.topology.internal.toolkit.info;

import javax.xml.bind.annotation.XmlNs;
