//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 01:06:02 PM PDT 
//


package com.ibm.streamsx.topology.internal.toolkit.info;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rootType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rootType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="toolkitDir"/>
 *     &lt;enumeration value="applicationDir"/>
 *     &lt;enumeration value="outputDir"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rootType")
@XmlEnum
public enum RootType {

    @XmlEnumValue("toolkitDir")
    TOOLKIT_DIR("toolkitDir"),
    @XmlEnumValue("applicationDir")
    APPLICATION_DIR("applicationDir"),
    @XmlEnumValue("outputDir")
    OUTPUT_DIR("outputDir");
    private final String value;

    RootType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RootType fromValue(String v) {
        for (RootType c: RootType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
