//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 01:06:02 PM PDT 
//


package com.ibm.streamsx.topology.internal.toolkit.info;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for toolkitInfoModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="toolkitInfoModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identity" type="{http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo}identityType"/>
 *         &lt;element name="dependencies" type="{http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo}dependenciesType"/>
 *         &lt;element name="resources" type="{http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo}resourcesType" minOccurs="0"/>
 *         &lt;element name="sabFiles" type="{http://www.ibm.com/xmlns/prod/streams/spl/toolkitInfo}sabFilesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name="toolkitInfoModel")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "toolkitInfoModelType", propOrder = {
    "identity",
    "dependencies",
    "resources",
    "sabFiles"
})
public class ToolkitInfoModelType {

    @XmlElement(required = true)
    protected IdentityType identity;
    @XmlElement(required = true)
    protected DependenciesType dependencies;
    protected ResourcesType resources;
    protected SabFilesType sabFiles;

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType }
     *     
     */
    public IdentityType getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType }
     *     
     */
    public void setIdentity(IdentityType value) {
        this.identity = value;
    }

    /**
     * Gets the value of the dependencies property.
     * 
     * @return
     *     possible object is
     *     {@link DependenciesType }
     *     
     */
    public DependenciesType getDependencies() {
        return dependencies;
    }

    /**
     * Sets the value of the dependencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependenciesType }
     *     
     */
    public void setDependencies(DependenciesType value) {
        this.dependencies = value;
    }

    /**
     * Gets the value of the resources property.
     * 
     * @return
     *     possible object is
     *     {@link ResourcesType }
     *     
     */
    public ResourcesType getResources() {
        return resources;
    }

    /**
     * Sets the value of the resources property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourcesType }
     *     
     */
    public void setResources(ResourcesType value) {
        this.resources = value;
    }

    /**
     * Gets the value of the sabFiles property.
     * 
     * @return
     *     possible object is
     *     {@link SabFilesType }
     *     
     */
    public SabFilesType getSabFiles() {
        return sabFiles;
    }

    /**
     * Sets the value of the sabFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link SabFilesType }
     *     
     */
    public void setSabFiles(SabFilesType value) {
        this.sabFiles = value;
    }

}
