before_install:
  - wget http://apache.osuosl.org//ant/binaries/apache-ant-1.10.6-bin.zip
  - unzip apache-ant-1.10.6-bin.zip
  - export PATH=`pwd`/apache-ant-1.10.6/bin:$PATH

language: python
python: "3.6"

install:
    - pip install flake8  # pytest  # add another testing frameworks later
before_script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script: ./test/python/travisci.sh
