# coding=utf-8
# Licensed Materials - Property of IBM
# Copyright IBM Corp. 2017
from typing import Any, Optional

from streamsx.topology.topology import Topology

def submit(ctxtype: Any, graph: Topology, config: Any=None, username: str=None, password: str=None) -> SubmissionResult: ...

class JobConfig(object):
    def __init__(self, job_name: str=None, job_group: str=None, preload: Any=bool, data_directory: str=None, tracing: Any=None) -> None: ...
    def tracing(self, level: Any) -> None: ...
    def target_pe_count(self, count: int=None) -> Optional[int] : ...
    def add(self, config: Any) -> Any: ...

class SubmissionResult(object):
    def __init__(self, results: Any) -> None: ...
    def job(self) -> Optional[Any]: ...

class ContextTypes(object): ...
class ConfigParams(object): ...

